GET http://localhost:3000/user
###
//creation roles
GET http://localhost:3000/api/roles
###
POST http://localhost:3000/api/auth/signup HTTP/1.1
content-type: application/json

{
    "username": "crisy",
    "password": "1234",
    "firstName": "yoel",
    "lastName" : "cristian",
    "dni": "40861016",
    "email": "cristianyoel@gmail.com",
    "cars": [],
    "roles": [
        "admin"
    ]
}
###
POST http://localhost:3000/api/auth/signin HTTP/1.1
content-type: application/json

{
    "email": "cristianyoel@gmail.com",
    "password": "1234"
}
###
PUT http://localhost:3000/user/60819787f4a8501334fc1d47/update HTTP/1.1
content-type: application/json

{
    "firstName": "cristian",
    "lastName" : "yoel",
    "dni": "40861016",
    "mail": "cristianyoel@gmail.com",
    "cars": [
        {
        "status": "INACTIVE",
        "_id": "608348c62189a30a8c75a6ec",
        "brand": "Ford",
        "model": "F-150",
        "fuel": "gasoil",
        "category": "4x4",
        "transmission": "Auto",
        "origin": "EE.UU",
        "year": "2005",
        "__v": 0
        }
    ]
}

###
DELETE http://localhost:3000/user/60819787f4a8501334fc1d47/delete HTTP/1.1
content-type: application/json

{
    
}