GET http://localhost:3000/user
###
POST http://localhost:3000/user/add HTTP/1.1
content-type: application/json

{
    "firstName": "yoel",
    "lastName" : "cristian",
    "dni": "40861016",
    "mail": "cristianyoel@gmail.com",
    "cars": []
}
###
PUT http://localhost:3000/user/:/update HTTP/1.1
content-type: application/json

{

}

###
DELETE http://localhost:3000/user/:/delete HTTP/1.1
content-type: application/json

{
    
}