GET http://localhost:3000/user
###
GET http://localhost:3000/
###
POST http://localhost:3000/userAdd HTTP/1.1
content-type: application/json

{
    "firstName": "yoel",
    "lastName" : "cristian",
    "dni": "40861016",
    "mail": "cristianyoel@gmail.com",
    "cars": "",
    "status": "ACTIVE" 
}